//! gABI validation for dynamic-array relationships.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValidationError {
    MalformedDynamicArray,
    MissingNullTerminator,
    ReservedTag { index: usize, raw: i64 },
    MissingStringTable,
    MissingSymbolTable,
    MissingStringTableSize,
    MissingSymbolEntrySize,
    MissingHashOrSymbolTableSize,
    SymbolEntrySizeMismatch { expected: u64, actual: u64 },
    SymbolTableSizeNotEntryMultiple,
    ExecutableMissingRelocationTable,
    RelocationMissingSize,
    RelocationMissingEntrySize,
    RelocationEntrySizeMismatch { expected: u64, actual: u64 },
    RelocationSizeNotEntryMultiple,
    RelocationWithAddendMissingSize,
    RelocationWithAddendMissingEntrySize,
    RelocationWithAddendEntrySizeMismatch { expected: u64, actual: u64 },
    RelocationWithAddendSizeNotEntryMultiple,
    JumpRelocationMissingSize,
    JumpRelocationMissingFormat,
    JumpRelocationInvalidFormat { raw: u64 },
    ReservedFlags { bits: u64 },
    InitializationArrayMissingSize,
    TerminationArrayMissingSize,
    PreInitializationArrayMissingSize,
    PreInitializationInSharedObject,
    InitializationArraySizeNotPointerMultiple,
    TerminationArraySizeNotPointerMultiple,
    PreInitializationArraySizeNotPointerMultiple,
    RelativeRelocationMissingSize,
    RelativeRelocationMissingEntrySize,
    RelativeRelocationEntrySizeMismatch,
    RelativeRelocationSizeNotEntryMultiple,
}
