[workspace]
members = ["example/server", "example/xelf"]

[package]
publish = true
license-file = "LICENSE"
authors = ["José Gois <ze.gois.00@gmail.com>"]
homepage = "https://userspace.builders"
repository = "https://github.com/ze-gois/rust_userspace"
description = "Standard library for userspace applications"
documentation = "https://docs.rs/bitflags"
name = "userspace"
readme = "README.md"
version = "0.1.1"
edition = "2024"
keywords = ["architecture", "operating_system"]
categories = ["no-std", "os"]

[lib]
name = "userspace"
path = "src/library.rs"
test = false

[[bin]]
name = "userspace"
path = "src/entry.rs"
test = false

[dependencies]

[workspace.dependencies]
userspace = { path = ".", version = "0.1.0" }
xelf = { path = "example/xelf", version = "0.1.0" }

[build-dependencies]
cc = "1.0"
# userspace_build = { package = "userspace", version = "0.1.1", rename = "userspace_build" }

[features]
default = ["no_std"]
no_std = []
with_std = []

[profile.dev]
# panic = "abort"

[profile.release]
# panic = "abort"
